### ISSUE TITLE
Hovering over a return value in a sequence diagram shows the value being returned

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#1353] opened 2023-09-05 20:47 UTC
### Issue

When hovering over a return label in the sequence diagram, the value should be displayed. For example, the value of `array` should be displayed on hover:

![Image](https://user-images.githubusercontent.com/573108/220173746-3b30648e-08d5-406e-8afa-3fd94c9029a5.png)

### Details

* Add a hover state to the return label so that the return value is displayed on hover.
* The code for the return label is [here](https://github.com/getappmap/appmap-js/blob/main/packages/components/src/components/sequence/ReturnLabel.vue).
* Please add Cypress tests in `packages/components/tests/e2e/specs`.

**Comment by kgilpin** [comment] 2023-09-08 18:23
@ahtrotta @brikelly is this a duplicate of https://github.com/getappmap/appmap-js/pull/1360?

**Comment by ahtrotta** [comment] 2023-09-08 18:29
No, 1360 is about a hover state for the call label and this is about a hover state for the return label

**Closed** 2023-09-13 14:38 UTC
Labels: enhancement, well-defined
