### ISSUE TITLE
EACCES: permission denied, scandir

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-js#806] opened 2022-10-20 19:33 UTC
From this [log](https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-10-20T16%3A59%3A03.454Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-10-20T16%3A59%3A03.454Z%22))%20and%20customDimensions%5B%22appmap.cli.sessionId%22%5D%20contains%20%22f714f763fccd2adf59c7db57c640e395a839d5219f625e0d6fb74fba1dbbfafd%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%7C%20project-reorder%20%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog) when recording.

```
EACCES: permission denied, scandir '/home/test/Documentos/Compania/CompaniaBackend/postgres-volume'
```

This is a bug. Sub-directories without read permission should not be raising an exception, they should just be skipped.

**Comment by apotterri** [comment] 2022-10-26 10:09
Duplicate of #803.

**Comment by ahtrotta** [comment] 2022-10-26 20:38
I think this is actually a bug and #803 isn't. So let's keep this one open and close #803.

**Comment by ahtrotta** [comment] 2022-10-26 20:40
Oops, sorry I mixed up my issue numbers. It looks like #812 isn't a bug, not #803.

**Closed by ahtrotta** 2022-10-26 20:40 UTC
Labels: bug
