### ISSUE TITLE
Sending a new message to Navie (Explain) should update the AppMap search results

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#1544] opened 2024-01-17 18:07 UTC
I sent a message to Navie (Explain) in `appmap-server` and got some AppMap search results:

![Image](https://github.com/getappmap/appmap-js/assets/45714532/c2e22259-35a5-4635-88b6-7e39809c1b8d)

When I send another message, the same AppMap search results are present:

![Image](https://github.com/getappmap/appmap-js/assets/45714532/2b2f0f75-8613-4aa1-b44e-6c9dab8c6f63)

**Comment by kgilpin** [comment] 2024-01-19 16:04
This is by design.

**Comment by dustinbyrne** [comment] 2024-01-19 22:12
wont fix

**Closed by dustinbyrne** 2024-01-19 22:12 UTC
Labels: navie
